"""add_trading_wallets

Revision ID: 7a3ee0b5d58f
Revises: 9be0511a48c6
Create Date: 2026-04-01 22:38:19.890396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a3ee0b5d58f"
down_revision: Union[str, None] = "9be0511a48c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=44), nullable=False),
        sa.Column("encrypted_private_key", sa.LargeBinary(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wallet_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_strategies_wallet_id", "trading_wallets", ["wallet_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_constraint("fk_strategies_wallet_id", type_="foreignkey")
        batch_op.drop_column("wallet_id")
    op.drop_table("trading_wallets")
    # ### end Alembic commands ###
